using D20Tek.Serialization.Generation;
using D20Tek.Serialization.Generator.Tests.TestSupport;

namespace D20Tek.Serialization.Generator.Tests;

[TestClass]
public sealed class RegistryEmitterTests
{
    [TestMethod]
    public void Emit_IncludesAutoGeneratedHeaderAndNullable()
    {
        // arrange
        var models = new[] { ModelFactory.Type("Person", "Sample") };

        // act
        var source = RegistryEmitter.Emit(models);

        // assert
        Assert.Contains("// <auto-generated/>", source);
        Assert.Contains("#nullable enable", source);
    }

    [TestMethod]
    public void Emit_EmitsAssemblyRegistryAttribute()
    {
        // arrange
        var models = new[] { ModelFactory.Type("Person", "Sample") };

        // act
        var source = RegistryEmitter.Emit(models);

        // assert
        Assert.Contains(
            "[assembly: global::D20Tek.Serialization.Generation.GeneratedSerializerRegistryAttribute(",
            source);
        Assert.Contains(
            "typeof(global::D20Tek.Serialization.Generated.GeneratedSerializerRegistry)",
            source);
    }

    [TestMethod]
    public void Emit_DeclaresRegistryInGeneratedNamespace()
    {
        // arrange
        var models = new[] { ModelFactory.Type("Person", "Sample") };

        // act
        var source = RegistryEmitter.Emit(models);

        // assert
        Assert.Contains("namespace D20Tek.Serialization.Generated", source);
        Assert.Contains("class GeneratedSerializerRegistry", source);
        Assert.Contains(
            "global::D20Tek.Serialization.Generation.IGeneratedSerializerRegistry",
            source);
    }

    [TestMethod]
    public void Emit_EmitsSingletonFieldPerModel()
    {
        // arrange
        var models = new[]
        {
            ModelFactory.Type("Person", "Sample"),
            ModelFactory.Type("Order", "Sample"),
        };

        // act
        var source = RegistryEmitter.Emit(models);

        // assert
        Assert.Contains("private static readonly PersonSerializer _Sample_Person = new PersonSerializer();", source);
        Assert.Contains("private static readonly OrderSerializer _Sample_Order = new OrderSerializer();", source);
    }

    [TestMethod]
    public void Emit_EmitsTryGetSerializerMethod()
    {
        // arrange
        var models = new[] { ModelFactory.Type("Person", "Sample") };

        // act
        var source = RegistryEmitter.Emit(models);

        // assert
        Assert.Contains(
            "public bool TryGetSerializer<T>(out global::D20Tek.Serialization.Generation.IGeneratedSerializer<T> serializer)",
            source);
    }

    [TestMethod]
    public void Emit_EmitsTypeCheckBranchPerModel()
    {
        // arrange
        var models = new[]
        {
            ModelFactory.Type("Person", "Sample"),
            ModelFactory.Type("Order", "Sample"),
        };

        // act
        var source = RegistryEmitter.Emit(models);

        // assert
        Assert.Contains("if (typeof(T) == typeof(global::Sample.Person))", source);
        Assert.Contains("if (typeof(T) == typeof(global::Sample.Order))", source);
    }

    [TestMethod]
    public void Emit_TypeCheckBranch_CastsAndReturnsTrue()
    {
        // arrange
        var models = new[] { ModelFactory.Type("Person", "Sample") };

        // act
        var source = RegistryEmitter.Emit(models);

        // assert
        Assert.Contains(
            "serializer = (global::D20Tek.Serialization.Generation.IGeneratedSerializer<T>)(object)_Sample_Person;",
            source);
        Assert.Contains("return true;", source);
    }

    [TestMethod]
    public void Emit_EmitsFallbackReturningFalse()
    {
        // arrange
        var models = new[] { ModelFactory.Type("Person", "Sample") };

        // act
        var source = RegistryEmitter.Emit(models);

        // assert
        Assert.Contains("serializer = null!;", source);
        Assert.Contains("return false;", source);
    }

    [TestMethod]
    public void Emit_GlobalNamespaceModel_UsesFlattenedTypeName()
    {
        // arrange
        var models = new[] { ModelFactory.Type("RootType", @namespace: null) };

        // act
        var source = RegistryEmitter.Emit(models);

        // assert
        Assert.Contains("private static readonly RootTypeSerializer _RootType = new RootTypeSerializer();", source);
        Assert.Contains("if (typeof(T) == typeof(global::RootType))", source);
    }
}
