using D20Tek.Serialization.Generation;
using D20Tek.Serialization.Generator.Tests.TestSupport;

namespace D20Tek.Serialization.Generator.Tests;

[TestClass]
public sealed class SerializerEmitterTests
{
    [TestMethod]
    public void Emit_IncludesAutoGeneratedHeaderAndNullable()
    {
        // arrange
        var model = ModelFactory.Type(members: ModelFactory.Member("Id", MemberStrategy.Int64));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("// <auto-generated/>", source);
        Assert.Contains("#nullable enable", source);
    }

    [TestMethod]
    public void Emit_DeclaresSerializerInGeneratedNamespace()
    {
        // arrange
        var model = ModelFactory.Type(members: ModelFactory.Member("Id", MemberStrategy.Int64));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("namespace D20Tek.Serialization.Generated", source);
        Assert.Contains("class SampleSerializer", source);
    }

    [TestMethod]
    public void Emit_ReferenceType_WriteIncludesNullGuard()
    {
        // arrange
        var model = ModelFactory.Type(
            isValueType: false,
            members: ModelFactory.Member("Id", MemberStrategy.Int64));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("if (value is null)", source);
        Assert.Contains("writer.WriteNull();", source);
    }

    [TestMethod]
    public void Emit_ValueType_WriteOmitsNullGuard()
    {
        // arrange
        var model = ModelFactory.Type(
            isValueType: true,
            members: ModelFactory.Member("Id", MemberStrategy.Int64));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.DoesNotContain("if (value is null)", source);
    }

    [TestMethod]
    public void Emit_ReferenceType_ReadIncludesNullCheck()
    {
        // arrange
        var model = ModelFactory.Type(
            isValueType: false,
            members: ModelFactory.Member("Id", MemberStrategy.Int64));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("if (reader.IsNull())", source);
        Assert.Contains("return null;", source);
    }

    [TestMethod]
    public void Emit_ValueType_ReadOmitsNullCheck()
    {
        // arrange
        var model = ModelFactory.Type(
            isValueType: true,
            members: ModelFactory.Member("Id", MemberStrategy.Int64));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.DoesNotContain("return null;", source);
    }

    [TestMethod]
    public void Emit_BooleanMember_WritesAndReadsBoolean()
    {
        // arrange
        var model = ModelFactory.Type(members: ModelFactory.Member("Flag", MemberStrategy.Boolean));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("writer.WriteBoolean(value.Flag);", source);
        Assert.Contains("result.Flag = reader.GetBoolean();", source);
    }

    [TestMethod]
    public void Emit_Int64Member_WritesAndReadsNumberWithCast()
    {
        // arrange
        var model = ModelFactory.Type(members: ModelFactory.Member("Count", MemberStrategy.Int64));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("writer.WriteNumber((long)value.Count);", source);
        Assert.Contains("result.Count = (int)reader.GetInt64();", source);
    }

    [TestMethod]
    public void Emit_DoubleMember_WritesAndReadsNumberWithCast()
    {
        // arrange
        var model = ModelFactory.Type(members: ModelFactory.Member("Ratio", MemberStrategy.Double));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("writer.WriteNumber((double)value.Ratio);", source);
        Assert.Contains("result.Ratio = (double)reader.GetDouble();", source);
    }

    [TestMethod]
    public void Emit_StringMember_WritesAndReadsString()
    {
        // arrange
        var model = ModelFactory.Type(members: ModelFactory.Member("Name", MemberStrategy.String));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("writer.WriteString(value.Name);", source);
        Assert.Contains("result.Name = reader.GetString();", source);
    }

    [TestMethod]
    public void Emit_EnumMember_WritesAndReadsNumberWithCast()
    {
        // arrange
        var model = ModelFactory.Type(members: ModelFactory.Member("Color", MemberStrategy.Enum));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("writer.WriteNumber((long)value.Color);", source);
        Assert.Contains("result.Color = (global::Demo.Color)reader.GetInt64();", source);
    }

    [TestMethod]
    public void Emit_NullableValueMember_EmitsNullBranchesAndValueAccess()
    {
        // arrange
        var model = ModelFactory.Type(
            members: ModelFactory.Member("Count", MemberStrategy.Int64, isNullable: true));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("if (value.Count is null)", source);
        Assert.Contains("if (!options.IgnoreNullValues)", source);
        Assert.Contains("writer.WriteNumber((long)value.Count.Value);", source);
        Assert.Contains("result.Count = null;", source);
    }

    [TestMethod]
    public void Emit_NullableStringMember_DoesNotAppendValueAccessor()
    {
        // arrange
        var model = ModelFactory.Type(
            members: ModelFactory.Member("Name", MemberStrategy.String, isNullable: true));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("writer.WriteString(value.Name);", source);
        Assert.DoesNotContain("value.Name.Value", source);
    }

    [TestMethod]
    public void Emit_RequiredMember_EmitsSeenFlagAndMissingCheck()
    {
        // arrange
        var model = ModelFactory.Type(
            members: ModelFactory.Member("Id", MemberStrategy.Int64, isRequired: true));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("var __seen_Id = false;", source);
        Assert.Contains("__seen_Id = true;", source);
        Assert.Contains("if (!__seen_Id)", source);
        Assert.Contains("Missing required property 'Id'.", source);
    }

    [TestMethod]
    public void Emit_NonRequiredMember_OmitsSeenFlag()
    {
        // arrange
        var model = ModelFactory.Type(
            members: ModelFactory.Member("Id", MemberStrategy.Int64, isRequired: false));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.DoesNotContain("__seen_Id", source);
    }

    [TestMethod]
    public void Emit_SerializedName_UsesLiteralName()
    {
        // arrange
        var model = ModelFactory.Type(
            members: ModelFactory.Member("Id", MemberStrategy.Int64, serializedName: "id"));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("writer.WritePropertyName(\"id\");", source);
        Assert.DoesNotContain("PropertyNamingPolicy?.ConvertName(\"Id\")", source);
    }

    [TestMethod]
    public void Emit_WithoutSerializedName_UsesNamingPolicyExpression()
    {
        // arrange
        var model = ModelFactory.Type(
            members: ModelFactory.Member("Id", MemberStrategy.Int64));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("options.PropertyNamingPolicy?.ConvertName(\"Id\") ?? \"Id\"", source);
    }

    [TestMethod]
    public void Emit_SerializedNameWithQuotes_EscapesLiteral()
    {
        // arrange
        var model = ModelFactory.Type(
            members: ModelFactory.Member("Id", MemberStrategy.Int64, serializedName: "a\"b\\c"));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("\"a\\\"b\\\\c\"", source);
    }

    [TestMethod]
    public void Emit_NoMembers_EmitsPropertySkipPath()
    {
        // arrange
        var model = ModelFactory.Type();

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("while (reader.TryReadPropertyName(out var __name))", source);
        Assert.Contains("reader.GetString();", source);
    }

    [TestMethod]
    public void Emit_MultipleMembers_UsesIfElseIfChain()
    {
        // arrange
        var model = ModelFactory.Type(
            members:
            [
                ModelFactory.Member("First", MemberStrategy.Int64),
                ModelFactory.Member("Second", MemberStrategy.String),
            ]);

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("if (__name == (", source);
        Assert.Contains("else if (__name == (", source);
    }

    [TestMethod]
    public void Emit_ImplementsGeneratedSerializerInterface()
    {
        // arrange
        var model = ModelFactory.Type(members: ModelFactory.Member("Id", MemberStrategy.Int64));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("global::D20Tek.Serialization.Generation.IGeneratedSerializer<global::Demo.Sample>", source);
    }

    [TestMethod]
    public void Emit_ReadReturnsNullableType()
    {
        // arrange
        var model = ModelFactory.Type(members: ModelFactory.Member("Id", MemberStrategy.Int64));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("public global::Demo.Sample? Read(", source);
    }

    [TestMethod]
    public void Emit_ValueType_ReadReturnsNonNullableType()
    {
        // arrange
        var model = ModelFactory.Type(
            isValueType: true,
            members: ModelFactory.Member("Id", MemberStrategy.Int64));

        // act
        var source = SerializerEmitter.Emit(model);

        // assert
        Assert.Contains("public global::Demo.Sample Read(", source);
        Assert.DoesNotContain("global::Demo.Sample? Read(", source);
    }
}
