namespace D20Tek.Serialization.Generation;

/// <summary>
/// Emits the per-assembly <c>IGeneratedSerializerRegistry</c> implementation that exposes every
/// generated serializer, along with the assembly-level attribute that advertises the registry for
/// runtime discovery.
/// </summary>
internal static class RegistryEmitter
{
    public const string GeneratedNamespace = SerializerEmitter.GeneratedNamespace;
    public const string RegistryTypeName = "GeneratedSerializerRegistry";

    public static string Emit(IReadOnlyList<SerializableTypeModel> models)
    {
        var writer = new SourceWriter();

        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
        writer.Line(
            $"[assembly: global::D20Tek.Serialization.Generation.GeneratedSerializerRegistryAttribute(" +
            $"typeof(global::{GeneratedNamespace}.{RegistryTypeName}))]");
        writer.Line();
        writer.Line($"namespace {GeneratedNamespace}");
        writer.OpenBrace();

        writer.Line("/// <summary>");
        writer.Line("/// Generated registry exposing all serializers produced for this assembly.");
        writer.Line("/// </summary>");
        writer.Line(
            $"internal sealed class {RegistryTypeName} : " +
            $"global::D20Tek.Serialization.Generation.IGeneratedSerializerRegistry");
        writer.OpenBrace();

        EmitSingletons(writer, models);
        writer.Line();
        EmitTryGet(writer, models);

        writer.CloseBrace();
        writer.CloseBrace();

        return writer.ToString();
    }

    private static void EmitSingletons(SourceWriter writer, IReadOnlyList<SerializableTypeModel> models)
    {
        foreach (var model in models)
        {
            writer.Line(
                $"private static readonly {model.SerializerTypeName} {FieldName(model)} = " +
                $"new {model.SerializerTypeName}();");
        }
    }

    private static void EmitTryGet(SourceWriter writer, IReadOnlyList<SerializableTypeModel> models)
    {
        writer.Line(
            "public bool TryGetSerializer<T>(" +
            "out global::D20Tek.Serialization.Generation.IGeneratedSerializer<T> serializer)");
        writer.OpenBrace();

        foreach (var model in models)
        {
            writer.Line($"if (typeof(T) == typeof({model.FullyQualifiedName}))");
            writer.OpenBrace();
            writer.Line(
                $"serializer = (global::D20Tek.Serialization.Generation.IGeneratedSerializer<T>)" +
                $"(object){FieldName(model)};");
            writer.Line("return true;");
            writer.CloseBrace();
            writer.Line();
        }

        writer.Line("serializer = null!;");
        writer.Line("return false;");
        writer.CloseBrace();
    }

    private static string FieldName(SerializableTypeModel model) => $"_{model.FlattenedIdentifier}";
}
