namespace D20Tek.Serialization.Generation;

/// <summary>
/// Emits the C# source for a generated <c>IGeneratedSerializer&lt;T&gt;</c> implementation for a
/// single <see cref="SerializableTypeModel"/>.
/// </summary>
internal static class SerializerEmitter
{
    public const string GeneratedNamespace = "D20Tek.Serialization.Generated";

    public static string Emit(SerializableTypeModel model)
    {
        var writer = new SourceWriter();
        var readReturnType = model.IsValueType ? model.FullyQualifiedName : model.FullyQualifiedName + "?";

        EmitHeader(writer);
        writer.Line($"namespace {GeneratedNamespace}");
        writer.OpenBrace();

        writer.Line("/// <summary>");
        writer.Line($"/// Generated serializer for <see cref=\"{model.FullyQualifiedName}\"/>.");
        writer.Line("/// </summary>");
        writer.Line(
            $"internal sealed class {model.SerializerTypeName} : " +
            $"global::D20Tek.Serialization.Generation.IGeneratedSerializer<{model.FullyQualifiedName}>");
        writer.OpenBrace();

        EmitWrite(writer, model);
        writer.Line();
        EmitRead(writer, model, readReturnType);

        writer.CloseBrace();
        writer.CloseBrace();

        return writer.ToString();
    }

    private static void EmitHeader(SourceWriter writer)
    {
        writer.Line("// <auto-generated/>");
        writer.Line("#nullable enable");
        writer.Line();
    }

    private static void EmitWrite(SourceWriter writer, SerializableTypeModel model)
    {
        writer.Line(
            $"public void Write(global::D20Tek.Serialization.IFormatWriter writer, " +
            $"{model.FullyQualifiedName} value, global::D20Tek.Serialization.SerializerOptions options)");
        writer.OpenBrace();

        if (!model.IsValueType)
        {
            writer.Line("if (value is null)");
            writer.OpenBrace();
            writer.Line("writer.WriteNull();");
            writer.Line("return;");
            writer.CloseBrace();
            writer.Line();
        }

        writer.Line("writer.WriteStartObject();");

        foreach (var member in model.Members)
        {
            EmitWriteMember(writer, member);
        }

        writer.Line("writer.WriteEndObject();");
        writer.CloseBrace();
    }

    private static void EmitWriteMember(SourceWriter writer, MemberModel member)
    {
        var access = $"value.{member.MemberName}";
        var nameExpr = SerializedNameExpression(member);

        if (member.IsNullable)
        {
            writer.Line($"if ({access} is null)");
            writer.OpenBrace();
            writer.Line("if (!options.IgnoreNullValues)");
            writer.OpenBrace();
            writer.Line($"writer.WritePropertyName({nameExpr});");
            writer.Line("writer.WriteNull();");
            writer.CloseBrace();
            writer.CloseBrace();
            writer.Line("else");
            writer.OpenBrace();
            writer.Line($"writer.WritePropertyName({nameExpr});");
            EmitWriteValue(writer, member, NonNullAccess(member, access));
            writer.CloseBrace();
        }
        else
        {
            writer.Line($"writer.WritePropertyName({nameExpr});");
            EmitWriteValue(writer, member, access);
        }
    }

    private static void EmitWriteValue(SourceWriter writer, MemberModel member, string valueExpr)
    {
        switch (member.Strategy)
        {
            case MemberStrategy.Boolean:
                writer.Line($"writer.WriteBoolean({valueExpr});");
                break;
            case MemberStrategy.Int64:
                writer.Line($"writer.WriteNumber((long){valueExpr});");
                break;
            case MemberStrategy.Double:
                writer.Line($"writer.WriteNumber((double){valueExpr});");
                break;
            case MemberStrategy.String:
                writer.Line($"writer.WriteString({valueExpr});");
                break;
            case MemberStrategy.Enum:
                writer.Line($"writer.WriteNumber((long){valueExpr});");
                break;
        }
    }

    private static void EmitRead(SourceWriter writer, SerializableTypeModel model, string readReturnType)
    {
        writer.Line(
            $"public {readReturnType} Read(global::D20Tek.Serialization.IFormatReader reader, " +
            $"global::D20Tek.Serialization.SerializerOptions options)");
        writer.OpenBrace();

        if (!model.IsValueType)
        {
            writer.Line("if (reader.IsNull())");
            writer.OpenBrace();
            writer.Line("return null;");
            writer.CloseBrace();
            writer.Line();
        }

        writer.Line($"var result = new {model.FullyQualifiedName}();");

        foreach (var member in model.Members)
        {
            if (member.IsRequired)
            {
                writer.Line($"var __seen_{member.MemberName} = false;");
            }
        }

        writer.Line("reader.ReadStartObject();");
        writer.Line("while (reader.TryReadPropertyName(out var __name))");
        writer.OpenBrace();

        if (model.Members.Count == 0)
        {
            writer.Line("reader.GetString();");
        }
        else
        {
            var first = true;
            foreach (var member in model.Members)
            {
                var keyword = first ? "if" : "else if";
                first = false;
                writer.Line($"{keyword} (__name == ({SerializedNameExpression(member)}))");
                writer.OpenBrace();
                EmitReadMember(writer, member);
                if (member.IsRequired)
                {
                    writer.Line($"__seen_{member.MemberName} = true;");
                }

                writer.CloseBrace();
            }

            writer.Line("else");
            writer.OpenBrace();
            writer.Line("reader.GetString();");
            writer.CloseBrace();
        }

        writer.CloseBrace();
        writer.Line("reader.ReadEndObject();");
        writer.Line();

        foreach (var member in model.Members)
        {
            if (member.IsRequired)
            {
                writer.Line($"if (!__seen_{member.MemberName})");
                writer.OpenBrace();
                writer.Line(
                    $"throw new global::D20Tek.Serialization.SerializationException(" +
                    $"\"Missing required property '{member.MemberName}'.\", \"$.{member.MemberName}\");");
                writer.CloseBrace();
            }
        }

        writer.Line("return result;");
        writer.CloseBrace();
    }

    private static void EmitReadMember(SourceWriter writer, MemberModel member)
    {
        var target = $"result.{member.MemberName}";

        if (member.IsNullable)
        {
            writer.Line("if (reader.IsNull())");
            writer.OpenBrace();
            writer.Line($"{target} = null;");
            writer.CloseBrace();
            writer.Line("else");
            writer.OpenBrace();
            writer.Line($"{target} = {ReadValueExpression(member)};");
            writer.CloseBrace();
        }
        else
        {
            writer.Line($"{target} = {ReadValueExpression(member)};");
        }
    }

    private static string ReadValueExpression(MemberModel member) =>
        member.Strategy switch
        {
            MemberStrategy.Boolean => "reader.GetBoolean()",
            MemberStrategy.Int64 => $"({UnderlyingNonNullType(member)})reader.GetInt64()",
            MemberStrategy.Double => $"({UnderlyingNonNullType(member)})reader.GetDouble()",
            MemberStrategy.String => "reader.GetString()",
            MemberStrategy.Enum => $"({UnderlyingNonNullType(member)})reader.GetInt64()",
            _ => "default",
        };

    private static string UnderlyingNonNullType(MemberModel member) =>
        member.FullyQualifiedTypeName.EndsWith("?", StringComparison.Ordinal)
            ? member.FullyQualifiedTypeName.Substring(0, member.FullyQualifiedTypeName.Length - 1)
            : member.FullyQualifiedTypeName;

    private static string NonNullAccess(MemberModel member, string access) =>
        member.Strategy == MemberStrategy.String ? access : $"{access}.Value";

    private static string SerializedNameExpression(MemberModel member) =>
        member.SerializedName is not null
            ? Literal(member.SerializedName)
            : $"options.PropertyNamingPolicy?.ConvertName({Literal(member.MemberName)}) ?? {Literal(member.MemberName)}";

    private static string Literal(string value) =>
        "\"" + value.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";
}
